3 domaća zadaca
ivannavratil/iOS-Vjestina-QuizApp pull request #1
Opened 2021-05-16 20:26 UTC by ivannavratil

Rješenje 3. domaće zadaće

2021-05-23 20:27 UTC, Kristijan22 requested changes

2021-05-23 20:27 UTC, Kristijan22 commented on QuizApp/Presenters/QuestionPresenter.swift
> +    }
Right now all of the information is already in the view controller and you are using the presenter to do very simple logic. The presenter should be the one keeping the reference to `Question` and ViewController should be asking the presenter for all the information. The point of the presenter is to take away dependencies from the view controller. In you view controller you should call presenter to ask "How many answers are there", "What is the question", "What are the answers?", "Hey, the user tapped this answer, is that correct?", and so on. Right now the view controller can answer all of that by never calling the presenter.

2021-05-23 20:27 UTC, Kristijan22 commented on QuizApp/Presenters/QuizPresenter.swift
> +class QuizPresenter{
This presenter isn't doing anything because all of the information is still in the view controller.

2021-05-23 20:27 UTC, Kristijan22 commented on QuizApp/Presenters/QuizResultPresenter.swift
> +    var networkService: NetworkServiceProtocol = NetworkService()
Use dependency injection to initialize this in the initializer.
```
convenience init(networkService: NetworkServiceProtocol) {}
```

2021-05-23 20:27 UTC, Kristijan22 commented on QuizApp/Presenters/QuizResultPresenter.swift
> +typealias QuizzResultPresenterDelegateT = QuizzResultPresenterDelegate & UIViewController
Same as above, no need for typealias.

2021-05-23 20:27 UTC, Kristijan22 commented on QuizApp/Presenters/QuizResultPresenter.swift
> +    var delegate:QuizzResultPresenterDelegateT!
Add `weak` to avoid strong reference cycle.

2021-05-23 20:27 UTC, Kristijan22 commented on QuizApp/Presenters/QuizResultPresenter.swift
> +            self.networkService.executeUrlRequest(request){(result:Result<EmptyResponse,RequestError>) in switch result {
There is a strong reference cycle here also. Use `[weak self]`

2021-05-23 20:27 UTC, Kristijan22 commented on QuizApp/Presenters/QuizResultPresenter.swift
> +        DispatchQueue.global(qos: .userInitiated).async {
Not needed and also a strong reference cycle. You are strongly capturing self here that is then passed down to async network call. This means self won't be able to be dismissed as long as the network call is in process.

2021-05-23 20:27 UTC, Kristijan22 commented on QuizApp/Presenters/QuizzesPresenter.swift
> +typealias QuizzesPresenterDelegateT = QuizzesPresenterDelegate & UIViewController
Same as above, typealias not needed.

2021-05-23 20:27 UTC, Kristijan22 commented on QuizApp/Presenters/QuizzesPresenter.swift
> +    var delegate:QuizzesPresenterDelegateT!
Add `weak` to avoid strong reference cycle.

2021-05-23 20:27 UTC, Kristijan22 commented on QuizApp/Presenters/QuizzesPresenter.swift
> +    var networkService: NetworkServiceProtocol = NetworkService()
Inject through the initializer.

2021-05-23 20:27 UTC, Kristijan22 commented on QuizApp/Presenters/QuizzesPresenter.swift
> +        DispatchQueue.global(qos: .userInitiated).async {
Not needed, it's fine to create a request on main thread.

2021-05-23 20:27 UTC, Kristijan22 commented on QuizApp/Presenters/QuizzesPresenter.swift
> +            self.networkService.executeUrlRequest(request){(result:Result<QuizzesResponse,RequestError>) in switch result {
Strong reference cycle. self owns network service, network service captures self. Use `[weak self]` to break the cycle.

2021-05-23 20:27 UTC, Kristijan22 commented on QuizApp/Presenters/SettingsPresenter.swift
> +typealias SettingsPresenterDelegateT = SettingsPresenterDelegate & UIViewController
Same as above, not needed.

2021-05-23 20:27 UTC, Kristijan22 commented on QuizApp/Presenters/SettingsPresenter.swift
> +        delegate?.logout()
This should be this presenters job. Take out the Router from VC and inject it into the presenter.

2021-05-23 20:27 UTC, Kristijan22 commented on QuizApp/Util.swift
> +        return alert;
`;` not needed in Swift

2021-05-23 20:27 UTC, Kristijan22 commented on QuizApp/ViewControllers/LoginViewController.swift
> +        self.presenter = LoginPresenter(delegate: self)
VC shouldn't need to create the presenter, the presenter should be injected into via dependency injection to the view controller. AppRouter should create the presenter before passing it to view controller. Then in the viewcontroller you can call:
`self.presenter.delegate = self` to set the delegate.

Same for all the other VC/presenter pairs.

2021-05-23 20:27 UTC, Kristijan22 commented on QuizApp/ViewControllers/LoginViewController.swift
> +//        presenter.tryUsernamePassword(username: "username", password: "password")
Remove unused code.

2021-05-23 20:27 UTC, Kristijan22 commented on QuizApp/ViewControllers/LoginViewController.swift
>      private var router : AppRouterProtocol!
Take this out and instead add it to the LoginPresenter.

2021-05-26 16:19 UTC, ivannavratil commented on QuizApp/Presenters/LoginPresenter.swift
> +    var networkService: NetworkServiceProtocol = NetworkService()
So I should send an instance of NetworkService from ViewController? And ViewController should receive it from AppRouter?

2021-05-29 10:41 UTC, merged